### ISSUE TITLE
"Responsive Equations" menu entry

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#117]
Where is that entry's text stored/generated?

Also, should we harmonize the naming of this option and Semantic-Collapse.js (where I would have assumed this comes from but I don't see it)?

**Comment by dpvc** [comment]
I changed the name from "Responsive Equations" to "Collapsible Math" in my branch, since the "auto collapse" is really the responsive one, and to make it shorter.

The string is in both the Semantic-Complexity and the Accessibility-Extension files.  Semantic-Collapse is the one that corresponds to "Auto Collapse".  The "Assistive" menu is the one that goes with the Assistive-Explore extension.

Yes, the names don't go as well with the menu items as I would like, either.  I suppose Semantic-Complexity could be renamed Semantic-Collapsible (ouch) or Semantic-Collapsibility or Semantic-CollapsibleMath, and Semantic-Collapse as Semantic-AutoCollapse.  Would Assistive-Explore be renamed just Assistive?

**Comment by pkra** [comment]
> I changed the name from "Responsive Equations" to "Collapsible Math" in my branch, since the "auto collapse" is really the responsive one, and to make it shorter.

Ah, that explains it. Thanks.

> Yes, the names don't go as well with the menu items as I would like, either. I suppose Semantic-Complexity could be renamed Semantic-Collapsible (ouch) or Semantic-Collapsibility or Semantic-CollapsibleMath, and Semantic-Collapse as Semantic-AutoCollapse. Would Assistive-Explore be renamed just Assistive?

Let's brainstorm on our own and discuss harmonizing the names on the next F2F.

**Comment by pkra** [comment]
Closing in favor of #118.
