### ISSUE TITLE
walker demo: disable AssistiveMML

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#35]
They are somewhat exclusive and the results can be confusing. But somehow the configuration I added to the  walker does not actually deactivate it.

**Comment by zorkow** [comment]
That should now work in #45

**Comment by pkra** [comment]
As I wrote, this somehow doesn't. @dpvc do combined and inline configs clash here?

**Comment by dpvc** [comment]
@pkra, can you provide the code that you used, and which file it is for?  I don't see anything anywhere for disabling AssistiveMML.  (@zorkow, this is the extension that adds the hidden MathML, and I don't see anything in #45 that would affect that.)  You would need to set `MathJax.Hub.config.menuSettings.assistiveMML` to either `true` or `false` to enable to disable the AssistiveMML extension.  Note that toggling this does *not* remove the hidden MathML that is in the page, or add it to already typeset math.  It only affect new math after the setting has changed.

**Comment by pkra** [comment]
>  can you provide the code that you used, and which file it is for? I don't see anything anywhere for disabling AssistiveMML.

[Here](https://github.com/mathjax/MathJax-RespEq/pull/45/files#diff-94d6de39b7cf6769e2fcdd16989a7444R8) but you already answered my question.

@zorkow can you update this to add  `MathJax.Hub.config.menuSettings.assistiveMML = false;` to the walker demo?

**Comment by dpvc** [comment]
Sorry, I thought you meant how to toggle the setting from within the page.  If you are configuring the page initially, use

```
MathJax.Hub.Config({AssistiveMML: {disabled: true}})
```

which is *almost* what you had (but you had `"AssistiveMML.js"` rather than `AssistiveMML`).  If you had already tried that, then perhaps you had set the Assistive MathML item in the MathJax menu sometime in the past (user preferences override the page setting).  In that case, toss the MathJax cookie and see if that helps.

**Comment by zorkow** [comment]
This did not work. 
I.e., 
MathJax.Hub.Config({ menuSettings: {CHTMLpreview: false}, AssistiveMML: {disabled: true});
failed, while
MathJax.Hub.Config({ menuSettings: {CHTMLpreview: false, assistiveMML: false}});
works. I now used the latter.
See #45

**Comment by dpvc** [comment]
> This did not work. 

If you have used the MathJax menu in the past to set/unset the AssisitiveMML option (via the hidden menu), then the cookie that is set for that will override the page-specific setting.

Your second version does override the user's setting (which I don't recommend).

Similarly, you should probably use

    MathJax.Hub.Cnfig({"fast-preview":{disabled: true}})

rather than setting the `CHTMLpreview` menu setting directly.  This allows user override.

**Comment by dpvc** [comment]
But I suppose since this is a demo page, you might not want to allow users to override the settings.

**Comment by pkra** [comment]
> you might not want to allow users to override the settings.

I'd agree because in the demo it leads to (unexplained) issues for users.
