### ISSUE TITLE
[a11y tool] NVDA bugs

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#39]
* NVDA consistently loses first speech text
  * could be fixed by adding a 100ms delay, cf. https://github.com/mathjax/MathJax-RespEq/pull/36/
* NVDA consistently loses speech text updates.
  * This is somewhat more erratic. It only happens in certain situations (and always when entering a lower level of an expression) but it is consistent, e.g.,
  * in the quadratic equation, `x` is never voiced when entering the first level (but exploring left, then right gets `x` voiced). Similarly, `-b` is never voiced when exploring the fraction's numerator.

Since no other AT has these problems, maybe it's a bug on NVDA's side. Let's reach out.

**Comment by jcsteh** [comment]
> NVDA consistently loses first speech text

I haven't had a chance to check this out myself. How are you doing the first push of text? If the live region isn't visible when the first update occurs, it's not technically a live region "update". NVDA only reports new text in live regions *after* they are visible. The reason for this is that otherwise, if there were many live regions (or a lot of text in one live region) on a page when it first loaded, they would all be spoken when the page loaded, thus flooding the user. In short, make sure the live region is visible *before* you push the first text. (Note that an empty div/span is not visible without CSS trickery or a no-break space.)

> NVDA consistently loses speech text updates.

If this happens in Chrome but not Firefox, it's almost certainly a Chrome bug, as NVDA uses the same implementation for both. Do you have a distilled test case that reproduces this? That would just make it easier to figure out where the issue is occurring. Otherwise, I'd need to familiarise myself with a lot more code to figure out what's going on.

**Comment by jcsteh** [comment]
(Edited previous comment to remove comment about divs/spans not being visible when they're empty. This isn't true for live regions.)

So, the following code works for me:

```
<div id="live" aria-live="polite"></div>
<button onClick="document.getElementById('live').textContent = 'foo';">Go</button>
```

Pressing the Go button speaks "foo" as expected.

**Comment by pkra** [comment]
@zorkow can comment on our implementation?

**Comment by zorkow** [comment]
Apologies for the delay. End of teaching term...

Originally we added the live region, initially empty, every time maths navigation mode was entered (and removed it on exit) and updated it during navigation. Adding one single live region to the dom when detecting a navigatable element and leaving it there seems to solve the problem in general.

As for the Chrome problem: Since it occurred erratically yet  deterministically, we implement a work around: We update the live region with a single space first and update it 100ms later with the string we actually want to speak. That seems to resolve the problem. Oddly it does not work when we update with an empty string first.

**Comment by pkra** [comment]
I think the only problem left is a new one: in Chrome, the aria-label is not read. But since no AT does that, I'm guessing that's Chrome's fault.

**Comment by pkra** [comment]
I believe this is all fixed now.
