### ISSUE TITLE
[a11y walker] improve extension for use in documents

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#65]
Using the walker is difficult in everyday documents because the extension does not have good defaults (i.e., dummy walker).

**Comment by zorkow** [comment]
We currently don't have a method to change walkers highlighting etc in
arbitrary documents. The question is: what do we want? Another menu entry,
keys?

**Comment by dpvc** [comment]
> We currently don't have a method to change walkers highlighting

Is this something that the author should set (to go along with the colors already in use in the page), or is it something the user should set?  Do different visual disabilities require different color combinations?

If it is a user setting, then it will have to be in the menus.  The walker can add menus (and submenus) to control this when it is loaded (so that they are only there when it is in use).

We haven't yet talked about how the walker is to be inserted into the page.  Is that up to the page author, or will the user be able to force that if it is not present?  Being int he third-party repository makes the later a bit more awkward.

**Comment by pkra** [comment]
> Is this something that the author should set (to go along with the colors already in use in the page), or is it something the user should set? 

Both (since both control CSS in many AT cases)

> Do different visual disabilities require different color combinations?

Yes (color blindness for example).

> Is that up to the page author, or will the user be able to force that if it is not present?

I'd say "definitely". But not necessarily through MathJax. As mentioned on #44, one use case is using the walker with mathjax-node output. In other words, I could also imagine a user extension or bookmarklet that loads the walker without touching MathJax itself (even if it's there).

**Comment by zorkow** [comment]
We now have the accessibility menu. 

Extension should be lightweight and switched on in context menu.

**Comment by pkra** [comment]
Fixed.
