### ISSUE TITLE
[a11y extension] add load complete call

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-RespEq#96]
[This files](https://github.com/mathjax/MathJax-accessibility/blob/master/MathJax-accessibility.js) needs at least a `loadComplete` call. Since we'll be pushing it to the CDN's third party folder, we need to decide on a path structure, e.g.,

````
MathJax.Callback.Queue(
  ["loadComplete",MathJax.Ajax,"[Contrib]/mathjax-a11y/MathJax-accessibility.js"]
);
```

**Comment by pkra** [comment]
Correction: folder, not repo.

**Comment by dpvc** [comment]
So to use this, one would do

```
<script type="text/x-mathjax-config">
   MathJax.Ajax.config.path["Contrib"] = "//cdn.mathjax.org/mathjax/contrib";
   MathJax.Hub.config.config.push("[Contrib]/mathjax-a11y/MathJax-accessibility.js");
</script>
```

Note that this has to be used as an entry in the `config` array (rather than `extensions`), since `MathJax-accessibility.js` modifies `extensions` (and that would be too late to have them loaded).

Alternatively, `MathJax-accessibility.js` could be made into a real extension by using 

```
MathJax.Ajax.config.path["RespEq"] = MathJax.Ajax.config.path["SRE"] = MathJax.Ajax.config.path["Contrib"] + '/mathjax-a11y/';
MathJax.Callback.Queue(
  MathJax.Ajax.Require("[RespEq]/Assistive-Explore.js"),
  MathJax.Ajax.Require("[RespEq]/Semantic-Collapse.js)",
  ["loadComplete",MathJax.Ajax,"[Contrib]/mathjax-a11y/MathJax-accessibility.js"]
);
```

so then you could do the standard

```
<script type="text/x-mathjax-config">
   MathJax.Ajax.config.path["Contrib"] = "//cdn.mathjax.org/mathjax/contrib";
   MathJax.Hub.config.extensions.push("[Contrib]/mathjax-a11y/MathJax-accessibility.js");
</script>
```

Also, I would not do the configuration

```
  MMLorHTML: {MSIE: "HTML"},
  AssistiveMML: {disabled: true},
  "fast-preview": {disabled: true},
```

in the extension, as the page author will not be able to override these (the page configuration will have been run first, and then these will override that).  Document that the page author should include these for efficiency, if desired.

For the same reason, I would not include `menuSettings` configuration here, either, as these will not be able to be overridden by the page author.  The defaults for the walker should be these values, so that you don't have to set them here.

**Comment by pkra** [comment]
Fixed.
